### ISSUE TITLE
Error in "python squelch_table_read.py"

### ISSUE THREAD

**Issue by frosty-13** [rebezhir/openquack#2]
Hello. Help me please. When trying to read, the following error appears:
![Error](https://github.com/rebezhir/openquack/assets/88665246/f53db2c7-7ff4-4364-a6a3-db5f05e7c08a)

**Comment by rebezhir** [comment]
Hmmm. Mine works. Which firmware are you using on your K5?
![Снимок](https://github.com/rebezhir/openquack/assets/6194851/63f78df4-8241-45e6-94db-12fedd2f1a8b)

**Comment by frosty-13** [comment]
I tried different firmware - fagci, k5_v2.01.26_publish, k5_v2.01.31_publish.

**Comment by rebezhir** [comment]
So why are you asking _me_, if this script is written by Tunas1337 and you're testing it with firmwares which are not mine?

**Comment by frosty-13** [comment]
Why do you steal other people's scripts and don't mention it anywhere?

**Comment by rebezhir** [comment]
Stealing OPEN SOURCE scripts? Are you mad?

**Comment by frosty-13** [comment]
Quiet, don't shout. You could have mentioned that this is not your script.
